export const ingestCopy = {
  commands: {
    douyinSubmitFallback: '抖音信号接入失败',
    fileSubmitFallback: '文件接入失败',
    conceptTitleRequired: '请输入概念名称',
    conceptSubmitFallback: '概念沉淀失败',
    sourceCollectFallback: '信息源扫描失败',
    douyinQueued: '抖音信号已进入处理轨道',
    fileQueued: '文件已进入处理轨道',
    conceptQueued: '概念节点已沉淀',
    sourceCollectDone: (count: number) => `扫描完成：新增 ${count} 条`,
  },
  detail: {
    bodyEmpty: '暂无转写原文',
    summaryLoading: 'AI 总结生成中',
    summaryEmpty: '该内容尚未生成 AI 总结',
    summaryAction: '生成 AI 总结',
    questionsLoading: '正在接入关联问题',
    questionsEmpty: '暂无推荐关联',
    chainLoading: '产业影响分析中',
    chainEmpty: '基于知识库分析该内容对产业链的影响',
    chainAction: '开始分析',
    loading: '加载内容详情',
    loadError: '加载内容详情失败',
    empty: '从左侧选择一条采集内容',
    preparing: '正在准备详情舱',
    titleFallback: '等待内容信号',
    summarizeFailed: 'AI 总结生成失败',
    contemplateFailed: '凝神静思失败',
    contemplateRequestFailed: '静思链路暂未响应',
    linkFailed: '关联失败',
    chainFailed: '产业分析失败',
    syncFailed: '同步失败',
    unknownError: '未知错误',
  },
  media: {
    waitingTitle: '等待内容信号',
    hasVideo: '该内容含视频，可展开播放',
    noVideo: '该内容暂无视频，右侧可阅读文本详情',
    pickContent: '从左侧选择一条采集内容',
  },
  queue: {
    waiting: '等待',
    stageWaiting: '等待处理阶段回传...',
    empty: '暂无处理队列',
    recentEmpty: '暂无完成记录',
    retryFailed: '重试失败',
    deleteFailed: '删除队列任务失败',
    taskDeleteFailed: '删除队列任务失败',
    pendingSummary: (count: number) => `${count} 项等待处理`,
  },
  stream: {
    loading: '正在同步内容流',
    interrupted: 'LINK INTERRUPTED',
    awaitingSignal: 'AWAITING SIGNAL',
    emptyTitle: '等待外部信号进入采集轨道',
    emptyDetail: '接入短视频、文件、概念或信息源扫描后，这里会出现标题索引。',
    backendDisconnected: '后端未连接，采集舱保持待命。',
    retry: '重新连接',
    loadError: '加载事件列表失败',
    deleteFailed: '删除失败',
  },
};
