[package]
name = "knowledge-intelligence"
version = "0.1.0"
description = "Knowledge Intelligence Desktop"
authors = ["samuelhung"]
edition = "2021"

[lib]
name = "knowledge_intelligence_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-opener = "2"
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
